version: '3.8'

volumes:
  postgres_data:
    driver: local
  
services:
  postgres:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB:
      POSTGRES_USER: 
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
  astrobot:
    image: astrobot
    command: ["./wait-for-it.sh", "postgres:5432", "--", "python3", "-m", "astrobot.bot"]
    environment:
      DATABASE_URL: postgresql://[ ASTRO_USER_NAME ]:[ ASTRO_USER_PASSWORD ]@postgres
      BOT_TOKEN:
    depends_on:
      - postgres